
version: '3.8'

services:
  weather-pipeline:
    build: 
      context: .  
    container_name: weather-pipeline  # Specify the container name
    restart: "no"  
    environment:
      - API_KEY=API_KEY # include correct API KEY

    entrypoint: >
      sh -c "for i in {1..4}; do python import.py; sleep 30; done"
